### ISSUE TITLE
Nullish coalescing operator (??) in `dist` files breaking current `create-react-app` setup

### ISSUE THREAD

**Issue by javierbyte** [pmndrs/use-cannon#198]
Hello, I'm using node `v14.17.0` and `react-scripts` `4.0.3`. In `1.2.4` I get an error related to the `??` operator when trying to run a project:

```
./node_modules/@react-three/cannon/dist/index.js 196:22
Module parse failed: Unexpected token (196:22)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|       id,
|       type,
>       target: target ?? 'bodies'
|     });
|     return () => {
```

This error is not present at least in `1.2.1`.

If this is not expected I should be able to make a PR to make sure to to transform those operators. Thanks for the great work!

Update: I created a PR #199

**Comment by stockHuman** [comment]
Hi there and thanks for the PR,

Node v14 [supports the nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator), as does the CRA setup [since 2019](https://github.com/facebook/create-react-app/releases/tag/v3.3.0), but indeed CRA's development targets combined with native support in some browsers seemingly trips up webpack..
[This solution](https://github.com/facebook/create-react-app/issues/9468#issuecomment-850278687) will likely work for you in the meantime.
