### ISSUE TITLE
CCD / Continous Collision Detection Enable

### ISSUE THREAD

**Issue by yyynnn** [pmndrs/use-cannon#391]
How to enable ccd on bodies?
Or this feature is not wired yet?
https://github.com/pmndrs/cannon-es/issues/93

**Comment by yyynnn** [comment]
is there a ways use cannonjs directly around and with use-cannon?

**Comment by isaac-mason** [comment]
`cannon-es` doesn't support CCD right now.

There was some work on the original repo for a WIP implementation, but it wasn't finished, and afaik hasn't been picked up again.

Regarding using cannon directly, because `@react-three/cannon` runs cannon in a web worker, all objects are created in the web worker and can't be interacted with directly.

If you find yourself needing to add new scripts or use other cannon libraries, you may be better off using cannon directly.

**Comment by isaac-mason** [comment]
You can track that issue to follow CCD support in `cannon-es`.

If/when CCD is added to `cannon-es`, this library can be updated to support it.

In the meantime, I think it makes sense to close this issue.
