### ISSUE TITLE
implement RaycastVehicle

### ISSUE THREAD

**Issue by dreammonkey** [pmndrs/use-cannon#87]
I'd like to know if there are plans to implement cannon's RaycastVehicle in this library ?
Maybe there is someone already working on it? I guess it would be an awesome feature ...

Great work BTW !

**Comment by dreammonkey** [comment]
Hello everyone, 

I had a go at this and I think I did a decent job at writing a proper API for the [RaycastVehicle](https://github.com/dreammonkey/cannon-es/blob/master/src/objects/RaycastVehicle.ts) class, but unfortunately the end result is all but perfect. That's why I'd like to ask you all for some input/feedback about this implementation. I know I must be making a silly mistake somewhere, but I'm currently not seeing it.

Note: I'm not a Typescript guru, so please let me know if you see things differently !

### The problem.
Currently the Raycast Vehicle is behaving more like a DancingRaycastRobot 🤖 :/

### The implementation

* Please check out [my fork](https://github.com/dreammonkey/use-cannon)
* The [useRaycastVehicle hook](https://github.com/dreammonkey/use-cannon/blob/aff8f6448c5b748c49499056f03265c6ee939b27/src/hooks.ts#L507).
* I also created [an example](https://github.com/dreammonkey/use-cannon/blob/master/examples/src/demos/Vehicle.js)
* The [worker implementation](https://github.com/dreammonkey/use-cannon/blob/aff8f6448c5b748c49499056f03265c6ee939b27/src/worker.js#L439).
* You'll also notice I made a change in the [cannon-es repo](https://github.com/dreammonkey/cannon-es/blob/66321c2be8a80acb44acd66867b1a93152dc2821/src/objects/RaycastVehicle.ts#L53)
Reason for this is to avoid using the vehicle.addToWorld(world) api (I've always considered this to be some sort of reversed api...) and the fact that the chassisBody is already added to the world by the useBox (or whatever you'd use) api, I believe using addToWorld would add it twice, which is clearly undesirable...

### Issues 
* During development I was really struggling with [the vehicle's coordinate system](https://github.com/dreammonkey/use-cannon/blob/aff8f6448c5b748c49499056f03265c6ee939b27/examples/src/demos/Vehicle.js#L138), I'm a Y-axis up kinda fellow, but when merely adding a plane to my scene it seems that z-axis is up by default... Although gravity is [0,-10,0].
* When adding the vehicle (as is) to the scene, its rotation always seems to be rotated 90° around the X-axis.
* Applying rotation on the chassisBody seems to make the vehicle land on all 4, but...
* When applying engine force/steering the funny 🤖 dancing starts to occur.

### Related
* I'm currently not implementing the [wheel-ground contact material](https://github.com/dreammonkey/use-cannon/blob/aff8f6448c5b748c49499056f03265c6ee939b27/src/worker.js#L93) (as in [Schteppe's original example](https://github.com/dreammonkey/cannon-es/blob/66321c2be8a80acb44acd66867b1a93152dc2821/examples/raycastVehicle.html#L24)) because of 2 reasons: 
  1. There is no API for it atm ?
  2. I've experimented with multiple contact materials (in relation to the vehicle class) and it seems not to be having any effect) in cannons-es.
* Maybe using the worker message channel for calling the vehicle api on enter frame is not the most performant use case. I've also tried implementing a version (not in this fork) where all user input is sent to the worker using an extra buffer. But this implementation is not easy to maintain (considering use cases where user input is not required or affects other parts of the program) (I know this bullet might not be very clear, let me know if you want me to clarify this thought).

### Conclusion
I'm not an expert at writing short issue reports 🤣 
I'm looking forward to your feedback on this/these subjects, I think it's great that you are keeping this beest alive and I'm committed to helping out, to my best abilities.

**Comment by dreammonkey** [comment]
@codynova I was preparing my fork to create a pull request when I noticed I was somewhat behind on you guys... When merging my branch with the upstream master it seems that the examples are broken... Are you aware of this, or is or just me ?

[use-cannon-1603734251286.log](https://github.com/pmndrs/use-cannon/files/5440461/use-cannon-1603734251286.log)

**Comment by Franckapik** [comment]
Thank you a lot for your contribution with the Vehicle feature ! I was looking for the example but it seem's broken on my side too!
Have you got an idea what's wrong on the Vehicle example and how to fix it ?
I am sure that i will use this new hook , wainting for it since a long time...
Thank you again!

**Comment by dreammonkey** [comment]
Hello @Franckapik ,

> Thank you a lot for your contribution with the Vehicle feature ! I was looking for the example but it seem's broken on my side too! (same log)

I believe the demos are broken because of an update to the react-three-fiber framework. I'm relatively new to the framework so fixing the demos is something I'd rather leave to the pros ;) Best thing to do I think is to create a separate issue about this (and hope that someone creates a fix...)

> Have you got an idea what's wrong on the Vehicle example and how to fix it ?

The Vehicle example works, if you'd checkout my [raycastvehicle branch](https://github.com/dreammonkey/cannon-es/tree/raycastvehicle) you should be able to build the examples and see the vehicle demo working (if that's not the case, let me know). Mind that the raycastvehicle branch is currently not up to date with use-cannon at the moment.

> I am sure that i will use this new hook , wainting for it since a long time...

Same here ;)

> Thank you again!

You're welcome !

**Comment by Franckapik** [comment]
I succeed to see the vehicle example by using your branch! It's indeed a react three fiver update issue! I'm not familiar with the git collaboration and development but i understand that we have to find why there is merging issue with v5 ...

Thank you @dreammonkey !

**Comment by Franckapik** [comment]
Hello @dreammonkey and @codynova !
So I looked at the code of the use-cannon examples and indeed saw that the versions were a bit late according to the progress of react three fiber:

Now:
    "@react-three / cannon": "file: ../ dist",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-router-dom": "^ 5.2.0",
    "react-three-fiber": "^ 5.0.1",
    "three": "0.118.3"

@dreammonkey , you forked the project when it was at version 4.2. Switching to current v5 returns several errors, the main one being the "init error" apparently linked to changes in the reconciler which requires an upload of react and react-dom to v17.

So I brought the[ following elements on my fork](https://github.com/Franckapik/use-cannon)
-change of versions in the examples at:
![image](https://user-images.githubusercontent.com/21478769/98656736-4c9aec80-2341-11eb-90f5-b1af165f98bb.png)

-sRBG removed from canvas.
-rename the import use-cannon to @ React-three / cannon
-small correction of a bug on MondayMorning.
-insertion of raycastVehicle which works well

However, I find a main error that appears randomly:

![image](https://user-images.githubusercontent.com/21478769/98656781-5de3f900-2341-11eb-93ab-2ada7dae130f.png)

@codynova , without wanting to ask you to look at the code, have you ever seen this error which seems to come from the provider?

Otherwise, a second smaller consequence is an alteration of the functionality of the mouse in the following examples:
-MondayMorning: the cursor is not follow enough the mouse.
-PingPong: the mouse does not seem to exist.

The other examples work!

In the meantime, I'm going to go to the raycastVehicle you wrote and if we can fix those little bugs, I'd love to see raycastVehicle in the master !!

Thanks again !

**Comment by codynova** [comment]
Hey @Franckapik, you can see the code that seems to be causing the error [here](https://github.com/pmndrs/use-cannon/blob/cf8a7482ed9eb8dfc2f39a58bec5b8027caee542/src/Provider.tsx#L144-L150)

This code was introduced in #100 to fix #99, but I don't personally have a VR headset, so wasn't much involved in that development

**Comment by Franckapik** [comment]
Thank you @codynova for this precision!
I will try to revert this commit tonight to see if i see a new error or not.
Like you, i don't have a VR headset so i won't be able to fix unless it is simply a change in useThree() regarding gl.xr which seems undefined since the last update.

**Comment by dreammonkey** [comment]
@Franckapik have you made any progress on this? I was having a go at updating my fork to be in sync with master and came across exactly the same issues you described [earlier](https://github.com/pmndrs/use-cannon/issues/87#issuecomment-724587647). Would be silly to do the same work twice ...

@codynova is someone currently working on fixing the examples ?
